name: test-run
on:
  workflow_dispatch:
    inputs:
      UNIT_TEST:
        description: "Run unit tests"
        required: true
        default: true
        type: boolean
      INTEGRATION_TEST:
        description: "Run integration tests"
        required: true
        default: true
        type: boolean
      INTEGRATION_TEST_EXISTING_IMAGE:
        description: "Run integration tests on existing image"
        required: true
        default: false
        type: boolean
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  unit-test:
    if: ${{ github.event_name == 'pull_request' || inputs.UNIT_TEST }}
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          exit 1  # Simulating failure

  unit-test-dashboard:
    runs-on: self-hosted
    needs: unit-test
    if: ${{ always() && needs.unit-test.result != 'skipped' }}
    steps:
      - name: Generate unit test dashboard
        run: echo "Generating unit test dashboard..."

  integration-test:
    if: ${{ github.event_name == 'pull_request' || inputs.INTEGRATION_TEST }}
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: echo "Running integration tests..."

  integration-test-dashboard:
    runs-on: self-hosted
    needs: integration-test
    if: ${{ always() && needs.integration-test.result != 'skipped' }}
    steps:
      - name: Generate integration test dashboard
        run: echo "Generating integration test dashboard..."

  integration-test-existing-image:
    if: ${{ inputs.INTEGRATION_TEST_EXISTING_IMAGE }}
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests on existing image
        run: echo "Running integration tests on existing image..."

  integration-test-existing-image-dashboard:
    runs-on: self-hosted
    needs: integration-test-existing-image
    if: ${{ always() && needs.integration-test-existing-image.result != 'skipped' }}
    steps:
      - name: Generate integration test dashboard for existing image
        run: echo "Generating integration test dashboard for existing image..."
