name: Master Dispatcher

on:
  workflow_dispatch:  # Can be triggered manually, or you can use push, schedule, etc.

jobs:
  trigger-downstream:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo A
        run: |
          curl -X POST https://api.github.com/repos/org-or-user/repo-a/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
          -d '{"event_type": "start_build", "client_payload": {"env": "production"}}'

      - name: Trigger workflow in Repo B
        run: |
          curl -X POST https://api.github.com/repos/org-or-user/repo-b/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
          -d '{"event_type": "start_tests", "client_payload": {"test_suite": "smoke"}}'
