name: Go Cross-Compile Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-go-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Create test Go file
        run: |
          cat <<EOF > main.go
          package main
          import (
            "fmt"
            "runtime"
          )
          func main() {
            fmt.Println("Hello from Go!")
            fmt.Println("Go version:", runtime.Version())
            fmt.Println("GOOS:", runtime.GOOS)
            fmt.Println("GOARCH:", runtime.GOARCH)
          }
          EOF

      - name: Build for Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o hello-linux main.go
          file hello-linux

      - name: Run binary
        run: ./hello-linux
