name: Test Docker Images

on:
  push:
    branches:
      - main

jobs:
  test-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Docker Python SDK
        run: pip install docker

      - name: Run Test Script
        env:
          IMAGE_NAME: your-image-name:tag
        run: |
          python test_docker_image.py $IMAGE_NAME \
            --test-files test_installations.py:/test_installations.py tools_expected.json:/tools_expected.json


  python test_docker_image.py your-image-name:tag \
  --test-files test_installations.py:/test_installations.py tools_expected.json:/tools_expected.json

