- name: Install java
  become: true
  ansible.builtin.dnf:
    name: "{{ java_package }}*{{ java_package_version }}*"
    state: present
    allowerasing: true
    disable_excludes: all
    install_weak_deps: "{{ java_force_installonly | default(true) }}"
  when:
    - not java_install_method == 'archive'
  register: java_installed
  args:
    creates: "{{ java_home }}/bin/java"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
