    - name: Install java
      become: true
      ansible.builtin.shell: "dnf install -y --allowerasing {{ java_package }}*{{ java_package_version }}* {{ java_force_installonly }} --disableexcludes=all"
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
      when:
        - not java_install_method == 'archive'
      register: java_installed
      args:
        creates: "{{ java_home }}/bin/java"
