- name: Add Adoptium YUM repository
  ansible.builtin.yum_repository:
    name: Adoptium
    description: Adoptium
    baseurl: "https://packages.adoptium.net/artifactory/rpm/{{ ansible_facts['os_family'] | lower | regex_replace('redhat', 'centos') }}/$releasever/$basearch"
    gpgcheck: yes
    gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
    enabled: yes
