name: Go Toolchain Integrity Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify-go:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Run `go version` and `go env`
        run: |
          go version
          go env

      - name: Run standard library tests
        run: go test std

      - name: Create and run basic Go program
        run: |
          echo 'package main; import "fmt"; func main() { fmt.Println("Hello from Go check") }' > main.go
          go build -o test-bin main.go
          ./test-bin
