jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        run: |
          LATEST_VERSION=$(gh release list --repo owner/repo --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest release: $LATEST_VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
